export const UPDATE_SESSION_LENGTH = 'UPDATE_SESSION_LENGTH';
export const UPDATE_BREAK_LENGTH = 'UPDATE_BREAK_LENGTH';

export const START_POMODORO = 'START_POMODORO';
export const STOP_POMODORO = 'STOP_POMODORO';
export const CLEAR_POMODORO = 'CLEAR_POMODORO';

export const TIMER_NOT_STARTED = 'TIMER_NOT_STARTED';
export const TIMER_STARTED = 'TIMER_STARTED';
export const TIMER_HOLD = 'TIMER_HOLD';
export const TIMER_CLEARED = 'TIMER_CLEARED';

export const SESSION_IN_PROGRESS = 'SESSION_IN_PROGRESS';
export const BREAK_IN_PROGRESS = 'BREAK_IN_PROGRESS';

export const SWITCH_POMODORO_STATE = 'SWITCH_POMODORO_STATE';

export const UPDATE_SECONDS_REMAINING = 'UPDATE_SECONDS_REMAINING';
